### ISSUE TITLE
Add ability for players to pick their role

### ISSUE THREAD

**Issue by lowkangn** [Soulcialize/souldragonknight#3]
Include an option for each player to pick whether to play as the Knight or the Soul Dragon. Suggestion for an additional scene where each player can make their selection before the game starts.

**Comment by kenneth-fung** [comment]
Partial progress made.

Implemented

- PlayerType is now selected in a new Room scene and saved to individual player's custom properties
- Room does not allow game to start unless all players in the room have selected their role and all roles have at least one player that selected it
- PlayerType for a player is cleared when they exit to main menu; they must reselect it when rejoining the room

Issues

- Players can't see what type they have selected in the Room UI
- Once a player has selected a role/type, other players should not be able to select that role/type
- When a player exits a room and rejoins the game, the game level reloads for all players in the game
  - This is because the Room scene doesn't take into account the possibility that one or more players in the room might already have started the game. In such a scenario, the Start button for starting the game in the Room scene should be changed to a Join button with different functionality.

**Comment by Eriksen2411** [comment]
Issues resolved for now:

- Players can't see what type they have selected in the Room UI
- Once a player has selected a role/type, other players should not be able to select that role/type (no need because they can both see each other roles and discuss to choose roles)
